version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12.16.2

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}-
      - run: npm ci
      - run:
          name: Run tests
          command: npm run test:ci
      - save_cache:
          paths:
            - ~/.npm
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
  release_dry:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}-
      - run: npm ci
      - run: npx semantic-release --dry-run
  release:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm i -g --prefix=$HOME/.local commitizen
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release_dry:
          requires:
            - test
          filters:
            branches:
              ignore: master
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
